backend:
  repo: eastend-street/portfolio
  name: git-gateway

media_folder: "src/images/uploads"
public_folder: "images/uploads"

collections:
  - label: Works
    name: work
    folder: src/data/_works
    create: true
    slug: "{{slug}}"
    editor:
      preview: true
    fields:
      - { label: Title, name: title, widget: string }
      - { label: Image, name: image, widget: image }
      - { label: Link, name: link, widget: string }
      - { label: Content, name: text, widget: markdown }
